version: "3.8"

services:
  postgres:
    ports:
      - "5432:5432"
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: yandex-eda
    environment:
      DB_PASSWORD: postgres
      AUTH_USERNAME: alice
      AUTH_PASSWORD: alice
    build:
      context: .
    depends_on:
      postgres:
          condition: service_healthy

volumes:
  db:
    driver: local